import java.util.ArrayList;
import java.util.UUID;

public class Bibliotheque {
    private ArrayList<Livre> catalogue;
    private ArrayList<Membre> membres;
    public Bibliotheque(){
        this.catalogue = new ArrayList<>();
        this.membres = new ArrayList<>();
    }
    public Bibliotheque(ArrayList<Livre> catalogue,ArrayList<Membre> membres){
        this.catalogue = catalogue;
        this.membres = membres;
    }
    public Bibliotheque(Bibliotheque other){
        this.catalogue = other.catalogue;
        this.membres = other.membres;
    }
    public ArrayList<Livre> getCatalogue(){
        return catalogue;
    }
    public ArrayList<Membre> getMembres(){
        return membres;
    }
    public void setCatalogue(ArrayList<Livre> catalogue){
        this.catalogue = catalogue;
    }
    public void setMembres(ArrayList<Membre> membres){
        this.membres = membres;
    }
    public void ajouterLivre(Livre livre){
        this.catalogue.add(livre);
    }

    public void inscrireMembre(Membre membre){
        this.membres.add(membre);
    }

    // Code generated By AI
    
    public Livre trouverLivreParId(UUID idLivre) {
        return this.catalogue.stream()
            .filter(l -> l.getId().equals(idLivre))
            .findFirst()
            .orElse(null);
    }

    public Membre trouverMembreParId(UUID idMembre) {
        return this.membres.stream()
            .filter(m -> m.getId().equals(idMembre))
            .findFirst()
            .orElse(null);
    }

    public void emprunterLivre(UUID idLivre, UUID idMembre)
            throws LivreIndisponibleException, LimiteEmpruntAtteinteException {

        Livre livre = trouverLivreParId(idLivre);
        Membre membre = trouverMembreParId(idMembre);

        if (livre == null || !livre.estDisponible()) {
            throw new LivreIndisponibleException("Le livre n'est pas disponible ou introuvable.");
        }
        if (membre == null || !membre.peutEmprunter()) {
            throw new LimiteEmpruntAtteinteException("Le membre a atteint sa limite maximale d'emprunts.");
        }

        livre.emprunter(membre);
        membre.ajouterEmprunt(livre);
    }

    public void rendreLivre(UUID idLivre, UUID idMembre) {
        Livre livre = trouverLivreParId(idLivre);
        Membre membre = trouverMembreParId(idMembre);

        if (livre != null && membre != null) {
            livre.rendre();
            membre.retirerEmprunt(livre);
        }
    }

    public ArrayList<Livre> rechercherParGenre(Genre genre) {
        return this.catalogue.stream()
            .filter(livre -> livre.getGenre() == genre)
            .collect(java.util.stream.Collectors.toCollection(ArrayList::new));
    }

    public ArrayList<Livre> rechercherParStatut(StatutLivre statut) {
        return this.catalogue.stream()
            .filter(livre -> livre.getStatus() == statut)
            .collect(java.util.stream.Collectors.toCollection(ArrayList::new));
    }

    public void afficherCatalogue() {
        System.out.println("=== CATALOGUE DE LA BIBLIOTHEQUE ===");
        for (Livre livre : catalogue) {
            System.out.println(livre);
        }
    }

}
